name: decimal
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: ^8.1.3
  bloc_test: ^9.1.6
  camera: ^0.11.0+1
  collection: ^1.18.0
  connectivity: ^3.0.6
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.0
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.0.2
  flutter_keyboard: ^2.0.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_lorem: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_zoom_drawer: ^3.2.0
  font_awesome_flutter: ^10.6.0
  gap: ^3.0.1
  get: ^4.6.6
  http: ^1.2.1
  image_picker: ^1.0.7
  meta: ^1.11.0
  mockito: ^5.4.4
  mocktail: ^1.0.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  skeletonizer: ^1.1.1
  supabase_flutter: ^2.5.1
  test: ^1.24.9
  uuid: ^4.3.3
  video_player: ^2.8.3
  youtube_player_flutter: ^9.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
flutter_native_splash:
  image: assets/images/logo.png
  color: "2A2A2A"

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf
