INSERT INTO pics (publication_id, content, tags) VALUES 
(19, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["science", "dreams", "innovation", "adventure"]'),
(23, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["survival", "technology", "innovation"]'),
(34, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["mystery", "survival"]'),
(37, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["cosmos", "science", "futurism", "history", "survival"]'),
(48, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["mystery", "dreams", "cosmos", "survival", "history"]'),
(52, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["adventure"]'),
(55, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["culture"]'),
(62, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["science", "culture", "nature", "history", "dreams"]'),
(63, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["history", "futurism"]'),
(64, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["history", "emotion", "science", "innovation"]'),
(70, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["history", "futurism", "fantasy"]'),
(76, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["futurism", "technology", "fantasy"]'),
(81, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["innovation", "emotion", "culture", "adventure"]'),
(85, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["innovation", "science", "culture", "futurism"]'),
(92, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["cosmos", "exploration"]'),
(104, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["cosmos", "emotion", "futurism", "fantasy", "innovation"]'),
(107, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["futurism", "culture", "fantasy", "history"]'),
(115, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["mystery"]'),
(119, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["mystery", "futurism", "innovation", "survival", "cosmos"]'),
(121, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["technology", "fantasy"]'),
(139, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["nature", "culture", "innovation", "futurism"]'),
(155, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["futurism", "innovation", "adventure", "mystery", "survival"]'),
(157, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["adventure", "history"]'),
(164, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["adventure", "culture", "survival", "emotion", "fantasy"]'),
(177, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["exploration", "survival", "fantasy", "science", "mystery"]'),
(187, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["technology"]'),
(208, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["science", "adventure", "mystery"]'),
(211, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["futurism", "exploration", "technology"]'),
(213, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["survival", "fantasy"]'),
(218, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["innovation", "technology", "science", "fantasy"]'),
(220, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["innovation"]'),
(221, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["nature", "history", "culture", "dreams", "futurism"]'),
(231, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["futurism", "mystery"]'),
(233, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["adventure", "survival", "culture"]'),
(237, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["emotion"]'),
(248, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["technology"]'),
(261, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["adventure", "survival"]'),
(266, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["fantasy"]'),
(289, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["mystery"]'),
(314, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["fantasy", "history", "dreams", "survival"]'),
(319, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["history", "mystery", "nature", "cosmos"]'),
(320, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["futurism"]'),
(324, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["innovation", "mystery", "fantasy", "adventure"]'),
(325, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["dreams", "cosmos", "fantasy", "mystery", "exploration"]'),
(326, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["history", "survival"]'),
(329, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["exploration"]'),
(331, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["mystery", "nature"]'),
(340, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["adventure", "mystery"]'),
(347, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["futurism", "innovation", "exploration"]'),
(352, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["science", "history", "technology", "adventure"]'),
(356, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["cosmos", "science", "nature", "emotion"]'),
(360, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["culture", "fantasy", "adventure", "futurism", "innovation"]'),
(362, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["culture", "science", "exploration", "history"]'),
(370, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["dreams"]'),
(390, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["culture"]'),
(394, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["survival", "history", "emotion"]'),
(406, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["science", "fantasy", "history", "mystery"]'),
(419, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["history"]'),
(457, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["futurism"]'),
(459, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["adventure", "survival"]'),
(469, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["culture", "science", "futurism", "innovation"]'),
(476, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["culture", "innovation", "nature", "history"]'),
(484, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["history", "cosmos", "innovation", "emotion", "mystery"]'),
(487, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["nature", "futurism", "adventure"]'),
(488, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["innovation", "cosmos"]'),
(489, 'The vibrant colors of the city at night, illuminating the streets with life and energy.', '["cosmos"]'),
(3, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["nature", "adventure", "futurism", "culture", "fantasy"]'),
(427, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["nature", "innovation"]'),
(434, 'A snapshot of daily life, portraying the simple joys and challenges of urban living.', '["mystery", "nature"]'),
(444, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["survival", "technology"]'),
(448, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["technology"]'),
(454, 'The delicate dance of flowers in the breeze, a testament to nature''s delicate balance.', '["dreams", "adventure", "survival", "culture"]'),
(492, 'The majestic presence of ancient forests, standing tall through centuries of history.', '["fantasy", "survival", "emotion", "adventure"]'),
(498, 'A moment of tranquility in the midst of nature, capturing the serene beauty of a hidden lake.', '["futurism", "culture", "fantasy", "emotion", "technology"]'),
(500, 'The stark beauty of desert landscapes, where life and resilience bloom against all odds.', '["innovation", "dreams", "culture", "fantasy"]');