INSERT INTO pictures (publication_id, url, content, tags, board_id) VALUES
(18, NULL, 'Good times and tan lines.', '["education", "entertainment", "education"]', 9),
(31, NULL, 'Living the dream.', '["education", "education", "tech"]', 4),
(3, NULL, 'Making memories.', '["education", "music", "music", "music"]', 9),
(32, NULL, 'Take only pictures, leave only footprints.', '["education", "music", "entertainment", "lifestyle", "tech"]', 3),
(27, NULL, 'High tides, good vibes.', '["education", "tech"]', 2),
(17, NULL, 'Do more things that make you forget to check your phone.', '["tech", "tech", "education"]', 7),
(54, NULL, 'Happiness is not a destination, it''s a way of life.', '["entertainment", "music"]', 9),
(31, NULL, 'Exploring the beauty of nature.', '["tech", "lifestyle", "entertainment", "entertainment", "music"]', 10),
(9, NULL, 'Dream. Plan. Do.', '["tech", "lifestyle", "entertainment"]', 7),
(37, NULL, 'Loving this aesthetic.', '["tech", "music", "lifestyle", "lifestyle", "music"]', 5),
(23, NULL, 'Go where you feel most alive.', '["lifestyle", "music", "tech", "entertainment"]', 8),
(57, NULL, 'High tides, good vibes.', '["lifestyle", "lifestyle", "music"]', 9),
(26, NULL, 'Don''t just exist, live.', '["tech", "tech", "education"]', 8),
(32, NULL, 'In the end, we only regret the chances we didn’t take.', '["lifestyle", "lifestyle", "entertainment", "music"]', 7),
(44, NULL, 'Get out there.', '["education", "entertainment", "tech", "music"]', 3),
(17, NULL, 'Exploring the beauty of nature.', '["music", "education", "music", "music", "education"]', 11),
(27, NULL, 'Loving this aesthetic.', '["lifestyle", "education"]', 10),
(35, NULL, 'Sunday Funday.', '["music", "education", "lifestyle", "lifestyle"]', 5),
(3, NULL, 'High tides, good vibes.', '["tech", "lifestyle", "entertainment", "music"]', 10),
(45, NULL, 'Let the good times roll.', '["lifestyle", "entertainment"]', 3),
(1, NULL, 'Smell the sea, feel the sky.', '["tech", "lifestyle", "education", "education", "education"]', 3),
(8, NULL, 'Dare to live the life you’ve always wanted.', '["tech", "lifestyle", "entertainment", "music"]', 9),
(56, NULL, 'Be happy, it drives people crazy.', '["music", "entertainment", "tech", "entertainment"]', 5),
(42, NULL, 'Dream. Plan. Do.', '["tech", "music", "lifestyle"]', 9),
(24, NULL, 'Stay golden.', '["education", "education"]', 11),
(36, NULL, 'In the end, we only regret the chances we didn’t take.', '["music", "education"]', 8),
(12, NULL, 'Wherever you go, go with all your heart.', '["entertainment", "lifestyle", "music"]', 2),
(51, NULL, 'Be happy, it drives people crazy.', '["music", "music", "entertainment", "music"]', 10),
(56, NULL, 'Living the dream.', '["education", "entertainment"]', 2),
(3, NULL, 'Sunkissed.', '["entertainment", "lifestyle", "education", "entertainment", "music"]', 9),
(17, NULL, 'Cherish every moment.', '["lifestyle", "education"]', 9),
(43, NULL, 'Weekend vibes.', '["music", "tech", "lifestyle"]', 8),
(47, NULL, 'Take only pictures, leave only footprints.', '["music", "music", "lifestyle"]', 7),
(52, NULL, 'Hakuna Matata.', '["tech", "entertainment", "tech"]', 6),
(57, NULL, 'Catching flights, not feelings.', '["tech", "entertainment", "music", "lifestyle", "lifestyle"]', 7),
(6, NULL, 'All about that wanderlust.', '["tech", "lifestyle", "lifestyle"]', 8),
(45, NULL, 'Just another magic Monday.', '["entertainment", "music", "entertainment", "tech", "education"]', 3),
(17, NULL, 'Lost and found.', '["entertainment", "tech", "lifestyle", "lifestyle", "tech"]', 8),
(24, NULL, 'Smell the sea, feel the sky.', '["music", "tech", "entertainment"]', 5),
(40, NULL, 'Let the good times roll.', '["lifestyle", "lifestyle", "music"]', 5),
(12, NULL, 'Collect moments, not things.', '["education", "education", "entertainment", "education", "music"]', 9),
(32, NULL, 'The best is yet to come.', '["tech", "education", "tech", "tech", "tech"]', 8),
(32, NULL, 'Good times and tan lines.', '["lifestyle", "lifestyle", "tech", "tech"]', 9),
(50, NULL, 'Exploring the beauty of nature.', '["lifestyle", "music"]', 8),
(58, NULL, 'Dare to dream.', '["education", "education"]', 11),
(19, NULL, 'Find your wild.', '["lifestyle", "entertainment", "lifestyle", "lifestyle", "education"]', 6),
(33, NULL, 'Weekend vibes.', '["lifestyle", "music"]', 3),
(58, NULL, 'Dream without fear.', '["music", "lifestyle", "music", "lifestyle"]', 2),
(10, NULL, 'Do more things that make you forget to check your phone.', '["music", "music", "entertainment", "education"]', 11),
(38, NULL, 'In the end, we only regret the chances we didn’t take.', '["tech", "education", "tech"]', 10),
(49, NULL, 'Dream big, little one.', '["music", "lifestyle", "entertainment"]', 2),
(48, NULL, 'Catching flights, not feelings.', '["entertainment", "lifestyle", "lifestyle", "entertainment"]', 2),
(28, NULL, 'Lost and found.', '["education", "entertainment"]', 6),
(55, NULL, 'Making memories.', '["entertainment", "music"]', 3);