INSERT INTO songs (publication_id, url, content, tags, duration) VALUES
(11, NULL, 'Stay golden.', '["tech", "education", "music", "lifestyle"]', 269),
(24, NULL, 'The simple things.', '["lifestyle", "entertainment", "music", "music"]', 180),
(47, NULL, 'Sunday Funday.', '["tech", "music", "music"]', 204),
(7, NULL, 'Your vibe attracts your tribe.', '["entertainment", "entertainment", "tech", "music"]', 270),
(28, NULL, 'Be yourself.', '["education", "music", "entertainment", "music"]', 292),
(9, NULL, 'In the end, we only regret the chances we didn’t take.', '["music", "tech", "lifestyle"]', 191),
(2, NULL, 'Dream big, little one.', '["entertainment", "entertainment", "entertainment", "lifestyle", "education"]', 230),
(22, NULL, 'The best is yet to come.', '["entertainment", "lifestyle", "lifestyle"]', 235),
(24, NULL, 'Life''s a journey.', '["music", "entertainment", "lifestyle", "education"]', 207),
(54, NULL, 'Living for these vibes.', '["tech", "lifestyle"]', 229),
(27, NULL, 'Sunday Funday.', '["music", "tech", "tech"]', 235),
(29, NULL, 'Cherish every moment.', '["music", "music"]', 216),
(57, NULL, 'Dream big, little one.', '["entertainment", "lifestyle", "lifestyle", "lifestyle", "tech"]', 280),
(14, NULL, 'Smell the sea, feel the sky.', '["lifestyle", "music"]', 237),
(34, NULL, 'Feeling grateful.', '["tech", "education", "tech", "lifestyle", "tech"]', 299),
(59, NULL, 'Making memories.', '["lifestyle", "lifestyle"]', 217),
(5, NULL, 'Go where you feel most alive.', '["music", "entertainment", "tech", "lifestyle"]', 220),
(29, NULL, 'Dream without fear.', '["music", "entertainment", "education"]', 260),
(26, NULL, 'The best is yet to come.', '["lifestyle", "lifestyle", "lifestyle", "tech", "education"]', 201),
(22, NULL, 'Do more things that make you forget to check your phone.', '["education", "tech", "tech", "lifestyle"]', 214),
(41, NULL, 'Dream big, little one.', '["education", "music", "entertainment", "music"]', 265),
(20, NULL, 'Captured moments.', '["education", "entertainment", "education", "education"]', 250),
(53, NULL, 'Living for these vibes.', '["education", "entertainment", "music", "education", "tech"]', 249),
(45, NULL, 'Loving this aesthetic.', '["lifestyle", "lifestyle", "entertainment", "tech"]', 256),
(55, NULL, 'Living the dream.', '["education", "lifestyle", "education", "tech"]', 226),
(11, NULL, 'Dream without fear.', '["entertainment", "music", "education", "tech"]', 226),
(58, NULL, 'Love without limits.', '["education", "education", "education"]', 239),
(12, NULL, 'Go where you feel most alive.', '["tech", "entertainment", "education"]', 265),
(31, NULL, 'The best is yet to come.', '["lifestyle", "entertainment"]', 258),
(30, NULL, 'Smell the sea, feel the sky.', '["music", "lifestyle", "lifestyle"]', 204),
(15, NULL, 'Never stop exploring.', '["entertainment", "tech"]', 228),
(55, NULL, 'The best is yet to come.', '["education", "music", "entertainment"]', 260),
(28, NULL, 'High tides, good vibes.', '["music", "entertainment", "lifestyle", "education"]', 206),
(7, NULL, 'Exploring the beauty of nature.', '["entertainment", "lifestyle", "tech"]', 286),
(38, NULL, 'Go where you feel most alive.', '["music", "education", "music"]', 248),
(1, NULL, 'Dream without fear.', '["education", "education", "lifestyle", "lifestyle"]', 269),
(5, NULL, 'Life is better when you’re laughing.', '["lifestyle", "education", "entertainment", "tech", "tech"]', 268),
(14, NULL, 'Another day, another adventure.', '["music", "lifestyle", "lifestyle", "lifestyle"]', 180),
(54, NULL, 'Dream big, little one.', '["education", "entertainment", "music"]', 228),
(44, NULL, 'Another day, another adventure.', '["education", "entertainment", "tech", "tech"]', 264),
(40, NULL, 'The best is yet to come.', '["entertainment", "entertainment", "lifestyle"]', 254),
(43, NULL, 'Keeping it simple.', '["entertainment", "education", "entertainment", "lifestyle", "lifestyle"]', 222),
(38, NULL, 'Stay golden.', '["education", "tech", "music"]', 233),
(32, NULL, 'Your vibe attracts your tribe.', '["tech", "entertainment", "education", "entertainment"]', 256),
(15, NULL, 'Better together.', '["entertainment", "music", "lifestyle", "music"]', 205),
(28, NULL, 'Be happy, it drives people crazy.', '["lifestyle", "tech", "entertainment"]', 196),
(55, NULL, 'Dream big, little one.', '["lifestyle", "tech", "lifestyle"]', 298),
(12, NULL, 'Life''s a journey.', '["lifestyle", "education", "lifestyle"]', 286),
(2, NULL, 'Your vibe attracts your tribe.', '["entertainment", "music", "music"]', 225),
(58, NULL, 'High tides, good vibes.', '["tech", "entertainment", "tech"]', 249),
(43, NULL, 'Just go.', '["music", "music", "music", "education", "lifestyle"]', 207),
(10, NULL, 'The best is yet to come.', '["entertainment", "entertainment", "education", "tech"]', 250),
(41, NULL, 'Dare to dream.', '["lifestyle", "tech", "education", "lifestyle"]', 259),
(7, NULL, 'Weekend vibes.', '["music", "lifestyle", "tech", "music"]', 195),
(6, NULL, 'The simple things.', '["lifestyle", "education", "entertainment", "tech"]', 295),
(7, NULL, 'Dream without fear.', '["education", "music"]', 255);