INSERT INTO stories (publication_id, content, tags, duration) VALUES 
(12, 'A deep dive into the legends of old, reimagined in a modern context, revealing timeless truths.', '["dreams", "cosmos"]', 10),
(22, 'The journey of rediscovering oneself after a life-changing event, set against the backdrop of a foreign land.', '["emotion", "cosmos", "innovation", "mystery"]', 9),
(28, 'A deep dive into the legends of old, reimagined in a modern context, revealing timeless truths.', '["science", "dreams", "nature"]', 11),
(39, 'A tale of innovation and determination, following a group of inventors on the cusp of a technological breakthrough.', '["mystery", "science", "dreams", "nature", "innovation"]', 13),
(46, 'An exploration of the unbreakable bonds of friendship that form in the most unlikely of circumstances.', '["culture", "innovation"]', 9),
(69, 'The mystery of an ancient artifact that holds the key to a secret long buried, unraveling across generations.', '["technology", "science", "dreams", "innovation"]', 9),
(72, 'The journey of rediscovering oneself after a life-changing event, set against the backdrop of a foreign land.', '["fantasy", "futurism", "science"]', 13),
(101, 'An exploration of the unbreakable bonds of friendship that form in the most unlikely of circumstances.', '["cosmos"]', 11),
(128, 'A deep dive into the legends of old, reimagined in a modern context, revealing timeless truths.', '["mystery", "emotion", "technology", "science", "fantasy"]', 9),
(141, 'A tale of innovation and determination, following a group of inventors on the cusp of a technological breakthrough.', '["adventure", "futurism"]', 11),
(175, 'The journey of rediscovering oneself after a life-changing event, set against the backdrop of a foreign land.', '["nature", "innovation", "emotion", "technology", "adventure"]', 9),
(185, 'An exploration of the unbreakable bonds of friendship that form in the most unlikely of circumstances.', '["exploration", "futurism", "cosmos", "survival"]', 9),
(189, 'An exploration of the unbreakable bonds of friendship that form in the most unlikely of circumstances.', '["dreams", "adventure", "cosmos"]', 10),
(192, 'A tale of innovation and determination, following a group of inventors on the cusp of a technological breakthrough.', '["survival", "innovation"]', 6),
(206, 'The journey of rediscovering oneself after a life-changing event, set against the backdrop of a foreign land.', '["mystery"]', 6),
(229, 'A deep dive into the legends of old, reimagined in a modern context, revealing timeless truths.', '["science", "emotion", "dreams", "cosmos"]', 8),
(239, 'A deep dive into the legends of old, reimagined in a modern context, revealing timeless truths.', '["adventure", "history", "survival", "innovation"]', 7),
(249, 'The challenges and triumphs of building a community from the ground up in a remote, untouched paradise.', '["futurism", "fantasy"]', 10),
(259, 'A deep dive into the legends of old, reimagined in a modern context, revealing timeless truths.', '["dreams"]', 8),
(267, 'The challenges and triumphs of building a community from the ground up in a remote, untouched paradise.', '["fantasy", "cosmos", "futurism", "technology"]', 7),
(270, 'The challenges and triumphs of building a community from the ground up in a remote, untouched paradise.', '["fantasy", "survival", "technology", "adventure", "history"]', 12),
(276, 'An exploration of the unbreakable bonds of friendship that form in the most unlikely of circumstances.', '["emotion", "culture", "exploration", "innovation", "cosmos"]', 9),
(283, 'A tale of innovation and determination, following a group of inventors on the cusp of a technological breakthrough.', '["mystery", "technology"]', 10),
(291, 'A deep dive into the legends of old, reimagined in a modern context, revealing timeless truths.', '["futurism", "science"]', 7),
(308, 'An exploration of the unbreakable bonds of friendship that form in the most unlikely of circumstances.', '["futurism", "cosmos"]', 8),
(313, 'The journey of rediscovering oneself after a life-changing event, set against the backdrop of a foreign land.', '["culture", "innovation", "mystery"]', 10),
(321, 'The mystery of an ancient artifact that holds the key to a secret long buried, unraveling across generations.', '["fantasy", "cosmos"]', 7),
(322, 'The journey of rediscovering oneself after a life-changing event, set against the backdrop of a foreign land.', '["technology", "fantasy", "mystery"]', 10),
(327, 'The challenges and triumphs of building a community from the ground up in a remote, untouched paradise.', '["cosmos", "innovation", "emotion", "fantasy", "technology"]', 8),
(365, 'The challenges and triumphs of building a community from the ground up in a remote, untouched paradise.', '["survival", "technology", "culture", "fantasy", "emotion"]', 9),
(366, 'A tale of innovation and determination, following a group of inventors on the cusp of a technological breakthrough.', '["futurism", "culture", "survival", "exploration", "science"]', 8),
(371, 'An exploration of the unbreakable bonds of friendship that form in the most unlikely of circumstances.', '["exploration"]', 13),
(377, 'The mystery of an ancient artifact that holds the key to a secret long buried, unraveling across generations.', '["mystery", "fantasy", "nature", "survival", "history"]', 9),
(383, 'The mystery of an ancient artifact that holds the key to a secret long buried, unraveling across generations.', '["fantasy", "exploration", "dreams", "emotion", "cosmos"]', 7),
(386, 'An exploration of the unbreakable bonds of friendship that form in the most unlikely of circumstances.', '["fantasy", "mystery", "dreams"]', 11),
(400, 'The mystery of an ancient artifact that holds the key to a secret long buried, unraveling across generations.', '["adventure", "emotion"]', 7),
(404, 'A tale of innovation and determination, following a group of inventors on the cusp of a technological breakthrough.', '["mystery", "dreams", "innovation", "science"]', 10),
(455, 'A tale of innovation and determination, following a group of inventors on the cusp of a technological breakthrough.', '["technology"]', 6),
(456, 'The challenges and triumphs of building a community from the ground up in a remote, untouched paradise.', '["history", "dreams", "culture", "nature"]', 7),
(462, 'The mystery of an ancient artifact that holds the key to a secret long buried, unraveling across generations.', '["survival", "technology", "futurism"]', 10),
(483, 'The mystery of an ancient artifact that holds the key to a secret long buried, unraveling across generations.', '["science", "culture", "futurism"]', 11),
(485, 'The challenges and triumphs of building a community from the ground up in a remote, untouched paradise.', '["technology", "adventure", "futurism", "cosmos"]', 10),
(1, 'A tale of innovation and determination, following a group of inventors on the cusp of a technological breakthrough.', '["innovation", "futurism", "nature", "dreams", "emotion"]', 9),
(7, 'The challenges and triumphs of building a community from the ground up in a remote, untouched paradise.', '["dreams", "nature", "technology"]', 9),
(431, 'A deep dive into the legends of old, reimagined in a modern context, revealing timeless truths.', '["exploration"]', 7),
(435, 'The journey of rediscovering oneself after a life-changing event, set against the backdrop of a foreign land.', '["history", "culture", "survival"]', 8),
(443, 'The mystery of an ancient artifact that holds the key to a secret long buried, unraveling across generations.', '["nature", "culture", "technology", "futurism"]', 9),
(452, 'The journey of rediscovering oneself after a life-changing event, set against the backdrop of a foreign land.', '["science", "futurism", "nature", "technology", "dreams"]', 12);