INSERT INTO stories (publication_id, url, content, tags, duration) VALUES
(41, NULL, 'Exploring the beauty of nature.', '["entertainment", "lifestyle", "music", "tech", "education"]', 12),
(58, NULL, 'Keeping it simple.', '["education", "entertainment", "lifestyle", "music", "music"]', 9),
(14, NULL, 'Catching flights, not feelings.', '["education", "entertainment", "entertainment", "education"]', 10),
(55, NULL, 'Cherish every moment.', '["music", "entertainment", "music"]', 20),
(21, NULL, 'You did not wake up today to be mediocre.', '["tech", "education", "tech", "education"]', 13),
(7, NULL, 'Life in color.', '["entertainment", "tech", "tech"]', 14),
(31, NULL, 'Just go.', '["tech", "education", "music", "entertainment", "entertainment"]', 18),
(29, NULL, 'Dare to dream.', '["education", "music"]', 15),
(51, NULL, 'Living the dream.', '["entertainment", "lifestyle", "tech"]', 18),
(28, NULL, 'Hakuna Matata.', '["lifestyle", "tech"]', 8),
(24, NULL, 'Living the dream.', '["music", "education", "lifestyle"]', 16),
(46, NULL, 'Keeping it simple.', '["education", "music", "education", "music", "tech"]', 10),
(39, NULL, 'Be yourself.', '["education", "entertainment"]', 21),
(17, NULL, 'Better together.', '["tech", "entertainment", "entertainment", "education"]', 13),
(58, NULL, 'Sunday Funday.', '["tech", "entertainment", "tech", "lifestyle"]', 20),
(54, NULL, 'The simple things.', '["entertainment", "entertainment", "entertainment", "music", "education"]', 11),
(40, NULL, 'Don''t just exist, live.', '["tech", "entertainment", "music", "entertainment", "lifestyle"]', 12),
(10, NULL, 'Loving this aesthetic.', '["music", "education"]', 14),
(13, NULL, 'Just another magic Monday.', '["entertainment", "lifestyle"]', 20),
(3, NULL, 'Wherever you go, go with all your heart.', '["lifestyle", "education", "entertainment", "lifestyle"]', 11),
(25, NULL, 'Making memories.', '["tech", "entertainment", "tech", "music"]', 18),
(25, NULL, 'Happiness is not a destination, it''s a way of life.', '["education", "music", "music"]', 14),
(18, NULL, 'Just go.', '["education", "tech", "education", "entertainment", "entertainment"]', 19),
(27, NULL, 'And so the adventure begins.', '["entertainment", "music", "music", "entertainment", "education"]', 19),
(60, NULL, 'Life''s a journey.', '["education", "lifestyle", "music", "tech"]', 21),
(12, NULL, 'Captured moments.', '["entertainment", "tech", "music"]', 15),
(28, NULL, 'Life in color.', '["lifestyle", "lifestyle", "music", "tech"]', 7),
(60, NULL, 'Take only pictures, leave only footprints.', '["lifestyle", "education", "music", "education", "music"]', 4),
(25, NULL, 'The future is bright.', '["music", "education", "education", "music"]', 14),
(41, NULL, 'Dare to live the life you’ve always wanted.', '["lifestyle", "music", "tech"]', 15),
(12, NULL, 'In the end, we only regret the chances we didn’t take.', '["lifestyle", "education", "tech"]', 6),
(25, NULL, 'Be yourself.', '["lifestyle", "entertainment", "education", "entertainment"]', 12),
(36, NULL, 'Wherever you go, go with all your heart.', '["music", "education", "music", "tech"]', 18),
(58, NULL, 'High tides, good vibes.', '["music", "education"]', 14),
(24, NULL, 'In the end, we only regret the chances we didn’t take.', '["music", "music"]', 7),
(24, NULL, 'The future is bright.', '["entertainment", "music", "lifestyle"]', 11),
(21, NULL, 'Collect moments, not things.', '["lifestyle", "entertainment", "entertainment", "lifestyle"]', 18),
(51, NULL, 'Catching flights, not feelings.', '["music", "education", "music", "education"]', 13),
(22, NULL, 'All about that wanderlust.', '["entertainment", "music", "tech"]', 9),
(17, NULL, 'You did not wake up today to be mediocre.', '["lifestyle", "lifestyle", "lifestyle"]', 16),
(34, NULL, 'Happiness is not a destination, it''s a way of life.', '["music", "music", "education", "entertainment"]', 10),
(39, NULL, 'Living for these vibes.', '["tech", "music", "entertainment", "education", "education"]', 10),
(42, NULL, 'Never stop exploring.', '["entertainment", "entertainment", "tech"]', 12),
(11, NULL, 'Keeping it simple.', '["tech", "music", "education", "tech"]', 16),
(14, NULL, 'All about that wanderlust.', '["lifestyle", "education", "lifestyle", "lifestyle", "education"]', 15),
(50, NULL, 'Stay golden.', '["tech", "tech", "music", "entertainment", "entertainment"]', 14);