INSERT INTO stories (publication_id, title, content, duration, tags) VALUES 
(1, 'Le jardin des secrets éternels', 'Une aventure inoubliable dans les montagnes.', 2, '["futuriste","magie","mystère"]'),
(7, 'Le pont entre les âmes', 'Le mystère de la maison abandonnée résolu.', 4, '["science-fiction","légende"]'),
(12, 'Les murmures du temps', 'L''amitié inattendue entre un chat et un chien.', 5, '["magie"]'),
(22, 'La danse des feuilles en automne', 'Le championnat du monde de tarte à la crème.', 10, '["nature","romantique"]'),
(28, 'Les clefs du royaume oublié', 'La découverte d''un nouveau monde sous-marin.', 5, '["historique"]'),
(39, 'Au-delà des étoiles perdues', 'Le voyage dans le temps qui a mal tourné.', 9, '["horreur","ancien"]'),
(46, 'La quête du phare cosmique', 'La recette secrète de la grand-mère révélée.', 2, '["mystère","ancien","futuriste"]'),
(69, 'Le souffle des forêts ancestrales', 'La mission spatiale à la recherche de vie extraterrestre.', 4, '["steampunk","mystère","futuriste"]'),
(72, 'L''éclipse des mondes parallèles', 'Le concours de danse qui a uni une ville.', 1, '["exploration"]'),
(101, 'Les chroniques des vents astraux', 'Le trésor caché dans le jardin de l''école.', 10, '["épique","ancien"]'),
(128, 'Les sentinelles de la lumière nocturne', 'La légende du fantôme du théâtre.', 9, '["ancien","nature"]'),
(141, 'L''odyssée des rêves oubliés', 'La machine à rêves devient réalité.', 9, '["ancien"]'),
(175, 'Les gardiens des cités englouties', 'L''île mystérieuse et ses secrets anciens.', 8, '["aventure"]'),
(185, 'Le carnaval des illusions', 'Le journal magique qui prédit l''avenir.', 1, '["exploration","fantaisie","magie"]'),
(189, 'Le voyageur des brumes matinales', 'Le festival des lanternes magiques.', 6, '["mythe"]'),
(192, 'Le chant des océans mystérieux', 'La forêt enchantée et ses créatures mystiques.', 3, '["horreur","science-fiction","aventure"]'),
(206, 'Les flammes de la destinée', 'L''évasion spectaculaire du zoo.', 10, '["épique"]'),
(229, 'Les architectes des univers infinis', 'La course de voitures volantes.', 2, '["horreur","historique","légende"]'),
(239, 'La légende des pierres chantantes', 'Le pique-nique qui a changé le monde.', 2, '["quête","nature","rêve"]'),
(249, 'La symphonie des galaxies lointaines', 'Le robot qui voulait être humain.', 8, '["rêve"]'),
(259, 'Le jardin des secrets éternels', 'Une aventure inoubliable dans les montagnes.', 1, '["exploration","nature","steampunk"]'),
(267, 'Le pont entre les âmes', 'Le mystère de la maison abandonnée résolu.', 8, '["romantique","épique","quête"]'),
(270, 'Les murmures du temps', 'L''amitié inattendue entre un chat et un chien.', 2, '["légende"]'),
(276, 'La danse des feuilles en automne', 'Le championnat du monde de tarte à la crème.', 4, '["exploration","romantique"]'),
(283, 'Les clefs du royaume oublié', 'La découverte d''un nouveau monde sous-marin.', 7, '["nature"]'),
(291, 'Au-delà des étoiles perdues', 'Le voyage dans le temps qui a mal tourné.', 3, '["futuriste","exploration"]'),
(308, 'La quête du phare cosmique', 'La recette secrète de la grand-mère révélée.', 8, '["romantique","nature"]'),
(313, 'Le souffle des forêts ancestrales', 'La mission spatiale à la recherche de vie extraterrestre.', 10, '["mythe","horreur","voyage"]'),
(321, 'L''éclipse des mondes parallèles', 'Le concours de danse qui a uni une ville.', 1, '["voyage","horreur"]'),
(322, 'Les chroniques des vents astraux', 'Le trésor caché dans le jardin de l''école.', 3, '["mystère","ancien"]'),
(327, 'Les sentinelles de la lumière nocturne', 'La légende du fantôme du théâtre.', 7, '["romantique","steampunk","surnaturel"]'),
(365, 'L''odyssée des rêves oubliés', 'La machine à rêves devient réalité.', 10, '["voyage","épique","nature"]'),
(366, 'Les gardiens des cités englouties', 'L''île mystérieuse et ses secrets anciens.', 4, '["science-fiction"]'),
(371, 'Le carnaval des illusions', 'Le journal magique qui prédit l''avenir.', 9, '["science-fiction","futuriste","romantique"]'),
(377, 'Le voyageur des brumes matinales', 'Le festival des lanternes magiques.', 9, '["rêve"]'),
(383, 'Le chant des océans mystérieux', 'La forêt enchantée et ses créatures mystiques.', 6, '["romantique","quête"]'),
(386, 'Les flammes de la destinée', 'L''évasion spectaculaire du zoo.', 7, '["surnaturel","science-fiction","futuriste"]'),
(400, 'Les architectes des univers infinis', 'La course de voitures volantes.', 1, '["voyage"]'),
(404, 'La légende des pierres chantantes', 'Le pique-nique qui a changé le monde.', 9, '["exploration","fantaisie","horreur"]'),
(431, 'La symphonie des galaxies lointaines', 'Le robot qui voulait être humain.', 5, '["exploration"]'),
(435, 'Le jardin des secrets éternels', 'Une aventure inoubliable dans les montagnes.', 8, '["magie"]'),
(443, 'Le pont entre les âmes', 'Le mystère de la maison abandonnée résolu.', 8, '["voyage"]'),
(452, 'Les murmures du temps', 'L''amitié inattendue entre un chat et un chien.', 6, '["futuriste"]'),
(455, 'La danse des feuilles en automne', 'Le championnat du monde de tarte à la crème.', 6, '["nature"]'),
(456, 'Les clefs du royaume oublié', 'La découverte d''un nouveau monde sous-marin.', 6, '["rêve","horreur"]'),
(462, 'Au-delà des étoiles perdues', 'Le voyage dans le temps qui a mal tourné.', 10, '["nature","historique","rêve"]'),
(483, 'La quête du phare cosmique', 'La recette secrète de la grand-mère révélée.', 7, '["horreur","épique"]'),
(485, 'Le souffle des forêts ancestrales', 'La mission spatiale à la recherche de vie extraterrestre.', 5, '["voyage","exploration"]');