INSERT INTO videos (publication_id, url, content, tags, duration) VALUES
(20, NULL, 'Life''s a journey.', '["music", "music", "tech", "education", "education"]', 670),
(59, NULL, 'Just breathe.', '["music", "entertainment", "music", "music", "tech"]', 664),
(44, NULL, 'The best is yet to come.', '["lifestyle", "entertainment", "education", "tech"]', 560),
(20, NULL, 'Don''t just exist, live.', '["music", "entertainment", "lifestyle", "education", "entertainment"]', 606),
(47, NULL, 'Captured moments.', '["education", "music", "tech", "tech", "lifestyle"]', 596),
(17, NULL, 'Find your wild.', '["lifestyle", "music", "music"]', 309),
(57, NULL, 'The simple things.', '["lifestyle", "tech", "entertainment", "lifestyle"]', 667),
(36, NULL, 'Weekend vibes.', '["lifestyle", "lifestyle", "music", "lifestyle"]', 751),
(20, NULL, 'Just breathe.', '["entertainment", "lifestyle", "lifestyle", "music", "music"]', 775),
(55, NULL, 'Dare to live the life you’ve always wanted.', '["lifestyle", "music", "tech"]', 537),
(55, NULL, 'The future is bright.', '["lifestyle", "education", "lifestyle"]', 658),
(3, NULL, 'Be happy, it drives people crazy.', '["lifestyle", "education", "tech", "entertainment"]', 565),
(24, NULL, 'And so the adventure begins.', '["entertainment", "entertainment", "music", "tech"]', 211),
(59, NULL, 'Living for these vibes.', '["education", "lifestyle", "tech"]', 443),
(9, NULL, 'Catching flights, not feelings.', '["lifestyle", "music", "tech", "lifestyle", "lifestyle"]', 900),
(60, NULL, 'Chasing sunsets.', '["music", "lifestyle", "lifestyle"]', 468),
(59, NULL, 'Find your wild.', '["education", "entertainment", "tech", "entertainment"]', 781),
(32, NULL, 'The simple things.', '["lifestyle", "music", "tech", "tech", "entertainment"]', 659),
(1, NULL, 'Don''t just exist, live.', '["music", "music", "tech", "education", "entertainment"]', 180),
(20, NULL, 'Take only pictures, leave only footprints.', '["lifestyle", "education"]', 180),
(16, NULL, 'Collect moments, not things.', '["tech", "music", "music"]', 617),
(58, NULL, 'Another day, another adventure.', '["education", "entertainment"]', 620),
(38, NULL, 'Feeling grateful.', '["lifestyle", "music", "music", "music", "education"]', 480),
(50, NULL, 'Dare to dream.', '["entertainment", "tech", "education", "tech", "music"]', 691),
(56, NULL, 'Catching flights, not feelings.', '["education", "tech", "education"]', 543),
(12, NULL, 'Life in color.', '["music", "music", "lifestyle", "entertainment"]', 591),
(59, NULL, 'High tides, good vibes.', '["education", "tech", "entertainment", "music", "lifestyle"]', 871),
(11, NULL, 'Captured moments.', '["entertainment", "tech", "lifestyle"]', 312),
(59, NULL, 'Living for these vibes.', '["music", "music", "education", "music"]', 489),
(55, NULL, 'Feeling grateful.', '["entertainment", "education", "music", "tech", "music"]', 570),
(43, NULL, 'Chasing sunsets.', '["tech", "education"]', 180),
(6, NULL, 'Catching flights, not feelings.', '["music", "lifestyle", "education", "music", "tech"]', 484),
(60, NULL, 'Lost and found.', '["entertainment", "education", "tech", "music", "education"]', 470),
(11, NULL, 'Love without limits.', '["music", "music", "lifestyle"]', 239),
(10, NULL, 'Be yourself.', '["tech", "music", "music", "entertainment"]', 369),
(23, NULL, 'You did not wake up today to be mediocre.', '["lifestyle", "music", "entertainment", "music", "entertainment"]', 503),
(42, NULL, 'The best is yet to come.', '["education", "education", "entertainment", "tech", "education"]', 559),
(12, NULL, 'Dream. Plan. Do.', '["music", "tech", "entertainment", "education", "education"]', 630),
(29, NULL, 'Chasing sunsets.', '["entertainment", "entertainment"]', 621),
(8, NULL, 'Feeling grateful.', '["tech", "tech"]', 271),
(45, NULL, 'Sunkissed.', '["music", "education", "tech", "entertainment", "entertainment"]', 406),
(45, NULL, 'Dare to dream.', '["education", "lifestyle", "entertainment"]', 900),
(8, NULL, 'Weekend vibes.', '["education", "education", "entertainment"]', 573),
(59, NULL, 'Making memories.', '["education", "education"]', 859),
(34, NULL, 'Happiness is not a destination, it''s a way of life.', '["education", "music", "music", "lifestyle"]', 536),
(9, NULL, 'High tides, good vibes.', '["entertainment", "lifestyle", "tech"]', 744),
(10, NULL, 'Life is better when you’re laughing.', '["entertainment", "entertainment"]', 874),
(34, NULL, 'Get out there.', '["lifestyle", "lifestyle"]', 505),
(21, NULL, 'Captured moments.', '["lifestyle", "tech", "education"]', 412),
(26, NULL, 'All about that wanderlust.', '["lifestyle", "lifestyle", "education"]', 509),
(41, NULL, 'Catching flights, not feelings.', '["tech", "education", "lifestyle"]', 517),
(21, NULL, 'Feeling grateful.', '["education", "entertainment"]', 669),
(8, NULL, 'Just another magic Monday.', '["education", "lifestyle", "tech", "tech", "education"]', 526),
(52, NULL, 'Find your wild.', '["education", "tech", "education"]', 482),
(28, NULL, 'Dream without fear.', '["lifestyle", "entertainment", "lifestyle", "education"]', 612),
(52, NULL, 'Sunkissed.', '["tech", "tech", "tech", "lifestyle"]', 498),
(52, NULL, 'Don''t just exist, live.', '["lifestyle", "music", "education", "music"]', 669),
(22, NULL, 'Do more things that make you forget to check your phone.', '["tech", "education", "education"]', 465),
(3, NULL, 'And so the adventure begins.', '["music", "entertainment"]', 689),
(2, NULL, 'Get out there.', '["tech", "lifestyle", "music", "education"]', 766),
(53, NULL, 'Exploring the beauty of nature.', '["entertainment", "tech"]', 614),
(21, NULL, 'Dare to dream.', '["tech", "entertainment", "education", "music", "lifestyle"]', 546),
(54, NULL, 'Captured moments.', '["lifestyle", "lifestyle"]', 744),
(27, NULL, 'Go where you feel most alive.', '["education", "education", "education"]', 576),
(33, NULL, 'Sunkissed.', '["lifestyle", "music", "music"]', 775),
(52, NULL, 'The best is yet to come.', '["lifestyle", "tech", "lifestyle", "entertainment", "music"]', 465),
(39, NULL, 'Life is better when you’re laughing.', '["music", "lifestyle", "lifestyle", "lifestyle", "education"]', 494),
(50, NULL, 'Another day, another adventure.', '["tech", "tech", "tech", "tech"]', 789),
(42, NULL, 'Find your wild.', '["education", "tech", "lifestyle"]', 712),
(13, NULL, 'High tides, good vibes.', '["entertainment", "entertainment", "music"]', 812),
(24, NULL, 'Love without limits.', '["lifestyle", "lifestyle", "entertainment"]', 451);