INSERT INTO vids (publication_id, url, content, tags, duration) VALUES
(1, NULL, 'Loving this aesthetic.', '["lifestyle", "music", "entertainment", "music", "entertainment"]', 15),
(60, NULL, 'Living for these vibes.', '["entertainment", "lifestyle"]', 15),
(18, NULL, 'All about that wanderlust.', '["lifestyle", "tech", "education", "tech", "education"]', 18),
(11, NULL, 'Lost and found.', '["tech", "entertainment"]', 13),
(6, NULL, 'Love without limits.', '["education", "music"]', 16),
(36, NULL, 'Be happy, it drives people crazy.', '["education", "education", "lifestyle"]', 14),
(11, NULL, 'Just another magic Monday.', '["entertainment", "music", "entertainment", "lifestyle", "entertainment"]', 11),
(16, NULL, 'Never stop exploring.', '["music", "tech"]', 15),
(23, NULL, 'Life in color.', '["tech", "education", "entertainment"]', 14),
(29, NULL, 'Do more things that make you forget to check your phone.', '["tech", "tech", "lifestyle", "education", "music"]', 13),
(23, NULL, 'Dream. Plan. Do.', '["music", "tech", "education", "music", "tech"]', 15),
(49, NULL, 'Just go.', '["music", "education"]', 11),
(26, NULL, 'Stay golden.', '["education", "entertainment", "entertainment", "entertainment", "education"]', 14),
(26, NULL, 'Sunkissed.', '["education", "tech", "lifestyle", "entertainment"]', 15),
(18, NULL, 'Lost and found.', '["music", "tech", "music"]', 17),
(17, NULL, 'Better together.', '["education", "education", "entertainment", "music"]', 19),
(7, NULL, 'You did not wake up today to be mediocre.', '["lifestyle", "entertainment"]', 18),
(35, NULL, 'Your vibe attracts your tribe.', '["education", "entertainment"]', 14),
(21, NULL, 'In the end, we only regret the chances we didn’t take.', '["music", "entertainment", "lifestyle", "lifestyle"]', 14),
(8, NULL, 'Just go.', '["lifestyle", "education", "entertainment"]', 15),
(5, NULL, 'Get out there.', '["entertainment", "tech"]', 15),
(27, NULL, 'Exploring the beauty of nature.', '["tech", "music", "education"]', 16),
(25, NULL, 'Find your wild.', '["music", "music", "lifestyle", "education", "education"]', 16),
(54, NULL, 'Chasing sunsets.', '["tech", "tech"]', 16),
(49, NULL, 'Lost and found.', '["education", "education"]', 14),
(20, NULL, 'You did not wake up today to be mediocre.', '["education", "education", "lifestyle", "entertainment"]', 14),
(36, NULL, 'Be yourself.', '["lifestyle", "tech"]', 16),
(9, NULL, 'Dare to live the life you’ve always wanted.', '["tech", "lifestyle", "tech", "entertainment", "music"]', 14),
(37, NULL, 'Your vibe attracts your tribe.', '["entertainment", "tech", "music"]', 12),
(44, NULL, 'Dream. Plan. Do.', '["education", "lifestyle"]', 16),
(39, NULL, 'Another day, another adventure.', '["education", "lifestyle"]', 16),
(51, NULL, 'Life''s a journey.', '["lifestyle", "music", "lifestyle"]', 15),
(53, NULL, 'Do more things that make you forget to check your phone.', '["entertainment", "tech", "lifestyle", "tech"]', 16),
(40, NULL, 'Stay golden.', '["tech", "lifestyle", "lifestyle"]', 14),
(50, NULL, 'Your vibe attracts your tribe.', '["lifestyle", "tech", "entertainment"]', 13),
(49, NULL, 'Get out there.', '["entertainment", "entertainment", "lifestyle"]', 14),
(1, NULL, 'Better together.', '["tech", "tech"]', 14),
(46, NULL, 'The simple things.', '["education", "lifestyle", "music", "entertainment"]', 15),
(50, NULL, 'Dream without fear.', '["lifestyle", "lifestyle"]', 16),
(4, NULL, 'Dream. Plan. Do.', '["music", "music"]', 15),
(53, NULL, 'Happiness is not a destination, it''s a way of life.', '["lifestyle", "lifestyle", "tech"]', 11),
(48, NULL, 'The best is yet to come.', '["tech", "lifestyle", "entertainment"]', 13),
(38, NULL, 'Hakuna Matata.', '["entertainment", "education", "music", "music", "entertainment"]', 14),
(22, NULL, 'Life is better when you’re laughing.', '["lifestyle", "entertainment", "lifestyle", "tech"]', 14),
(4, NULL, 'Just go.', '["music", "education", "entertainment"]', 12),
(5, NULL, 'Living for these vibes.', '["entertainment", "music", "entertainment", "lifestyle"]', 12),
(39, NULL, 'Loving this aesthetic.', '["tech", "entertainment", "music"]', 13),
(38, NULL, 'Keeping it simple.', '["music", "entertainment", "music", "lifestyle"]', 11),
(60, NULL, 'Sunday Funday.', '["entertainment", "entertainment", "education", "education", "education"]', 16),
(51, NULL, 'Good times and tan lines.', '["tech", "music"]', 13),
(28, NULL, 'Cherish every moment.', '["education", "tech", "lifestyle", "education", "education"]', 15),
(2, NULL, 'Better together.', '["entertainment", "education", "lifestyle"]', 11),
(13, NULL, 'The simple things.', '["education", "tech", "education", "tech", "lifestyle"]', 12),
(57, NULL, 'Making memories.', '["entertainment", "lifestyle", "tech"]', 15),
(2, NULL, 'Don''t just exist, live.', '["music", "music", "music", "lifestyle", "tech"]', 15),
(12, NULL, 'Love without limits.', '["music", "education", "tech"]', 13),
(4, NULL, 'Hakuna Matata.', '["music", "lifestyle", "education", "tech", "music"]', 18),
(17, NULL, 'Be happy, it drives people crazy.', '["education", "entertainment", "lifestyle", "lifestyle", "entertainment"]', 12),
(45, NULL, 'Collect moments, not things.', '["education", "tech", "entertainment", "entertainment"]', 15),
(17, NULL, 'Get out there.', '["education", "tech", "lifestyle", "lifestyle", "education"]', 12),
(19, NULL, 'Exploring the beauty of nature.', '["lifestyle", "entertainment", "entertainment"]', 14),
(25, NULL, 'Loving this aesthetic.', '["lifestyle", "lifestyle", "entertainment", "tech"]', 16),
(3, NULL, 'Feeling grateful.', '["lifestyle", "education"]', 14),
(28, NULL, 'Just another magic Monday.', '["education", "tech", "education"]', 13),
(50, NULL, 'Living the dream.', '["education", "music", "music"]', 13),
(18, NULL, 'Cherish every moment.', '["lifestyle", "music", "music", "education", "education"]', 14),
(32, NULL, 'Sunkissed.', '["entertainment", "education", "music", "music"]', 11),
(39, NULL, 'Just breathe.', '["entertainment", "tech", "tech", "education", "entertainment"]', 14),
(12, NULL, 'Be yourself.', '["education", "music", "education", "music", "tech"]', 13);